In [4]:
from ucimlrepo import fetch_ucirepo 

In [3]:
!pip install ucimlrepo

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   --- ------------------------------------ 1.0/11.5 MB 5.6 MB/s eta 0:00:02
   --------- ------------------------------ 2.6/11.5 MB 6.6 MB/s eta 0:00:02
   -------------- ------------------------- 4.2/11.5 MB 6.8 MB/s eta 0:00:02
   ------------------- -------------------- 5.5/11.5 MB 6.9 MB/s eta 0:00:01
   ----------------------- ---------------- 6.8/11.5 MB 6.7 MB/s eta 0:00:01
   ----------------------------- ---------- 8.4/11.5 MB 6.6 MB/s eta 0:00:01
   --------------------------------- ------ 9.7/11.5 MB 6.6 MB/s eta 0:00:01
   -------------------------------------- - 11.0/11.5 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 6.4 MB/s eta 0:00:00
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.6 MB 7.5 MB/s eta 0:00:02
   -------


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
#fetch dataset
breast_cancer_wisconsin_diagnostic = fetch_ucirepo(id=17)

In [15]:
# data (as pandas dataframes) 
X1 = breast_cancer_wisconsin_diagnostic.data.features 
y1 = breast_cancer_wisconsin_diagnostic.data.targets

In [16]:
X1

radius1  texture1  perimeter1   area1  smoothness1  compactness1  \
0      17.99     10.38      122.80  1001.0      0.11840       0.27760   
1      20.57     17.77      132.90  1326.0      0.08474       0.07864   
2      19.69     21.25      130.00  1203.0      0.10960       0.15990   
3      11.42     20.38       77.58   386.1      0.14250       0.28390   
4      20.29     14.34      135.10  1297.0      0.10030       0.13280   
..       ...       ...         ...     ...          ...           ...   
564    21.56     22.39      142.00  1479.0      0.11100       0.11590   
565    20.13     28.25      131.20  1261.0      0.09780       0.10340   
566    16.60     28.08      108.30   858.1      0.08455       0.10230   
567    20.60     29.33      140.10  1265.0      0.11780       0.27700   
568     7.76     24.54       47.92   181.0      0.05263       0.04362   

     concavity1  concave_points1  symmetry1  fractal_dimension1  ...  radius3  \
0       0.30010          0.14710     0.2419             0.07871  ...   25.380   
1       0.08690          0.07017     0.1812             0.05667  ...   24.990   
2       0.19740          0.12790     0.2069             0.05999  ...   23.570   
3       0.24140          0.10520     0.2597             0.09744  ...   14.910   
4       0.19800          0.10430     0.1809             0.05883  ...   22.540   
..          ...              ...        ...                 ...  ...      ...   
564     0.24390          0.13890     0.1726             0.05623  ...   25.450   
565     0.14400          0.09791     0.1752             0.05533  ...   23.690   
566     0.09251          0.05302     0.1590             0.05648  ...   18.980   
567     0.35140          0.15200     0.2397             0.07016  ...   25.740   
568     0.00000          0.00000     0.1587             0.05884  ...    9.456   

     texture3  perimeter3   area3  smoothness3  compactness3  concavity3  \
0       17.33      184.60  2019.0      0.16220       0.66560      0.7119   
1       23.41      158.80  1956.0      0.12380       0.18660      0.2416   
2       25.53      152.50  1709.0      0.14440       0.42450      0.4504   
3       26.50       98.87   567.7      0.20980       0.86630      0.6869   
4       16.67      152.20  1575.0      0.13740       0.20500      0.4000   
..        ...         ...     ...          ...           ...         ...   
564     26.40      166.10  2027.0      0.14100       0.21130      0.4107   
565     38.25      155.00  1731.0      0.11660       0.19220      0.3215   
566     34.12      126.70  1124.0      0.11390       0.30940      0.3403   
567     39.42      184.60  1821.0      0.16500       0.86810      0.9387   
568     30.37       59.16   268.6      0.08996       0.06444      0.0000   

     concave_points3  symmetry3  fractal_dimension3  
0             0.2654     0.4601             0.11890  
1             0.1860     0.2750             0.08902  
2             0.2430     0.3613             0.08758  
3             0.2575     0.6638             0.17300  
4             0.1625     0.2364             0.07678  
..               ...        ...                 ...  
564           0.2216     0.2060             0.07115  
565           0.1628     0.2572             0.06637  
566           0.1418     0.2218             0.07820  
567           0.2650     0.4087             0.12400  
568           0.0000     0.2871             0.07039  

[569 rows x 30 columns]

In [7]:
#metadata
print(breast_cancer_wisconsin_diagnostic.metadata) 

{'uci_id': 17, 'name': 'Breast Cancer Wisconsin (Diagnostic)', 'repository_url': 'https://archive.ics.uci.edu/dataset/17/breast+cancer+wisconsin+diagnostic', 'data_url': 'https://archive.ics.uci.edu/static/public/17/data.csv', 'abstract': 'Diagnostic Wisconsin Breast Cancer Database.', 'area': 'Health and Medicine', 'tasks': ['Classification'], 'characteristics': ['Multivariate'], 'num_instances': 569, 'num_features': 30, 'feature_types': ['Real'], 'demographics': [], 'target_col': ['Diagnosis'], 'index_col': ['ID'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 1993, 'last_updated': 'Fri Nov 03 2023', 'dataset_doi': '10.24432/C5DW2B', 'creators': ['William Wolberg', 'Olvi Mangasarian', 'Nick Street', 'W. Street'], 'intro_paper': {'ID': 230, 'type': 'NATIVE', 'title': 'Nuclear feature extraction for breast tumor diagnosis', 'authors': 'W. Street, W. Wolberg, O. Mangasarian', 'venue': 'Electronic imaging', 'year': 1993, 'journal': None, 'DOI': '1

In [8]:
# variable information 
print(breast_cancer_wisconsin_diagnostic.variables.name) 

0                     ID
1              Diagnosis
2                radius1
3               texture1
4             perimeter1
5                  area1
6            smoothness1
7           compactness1
8             concavity1
9        concave_points1
10             symmetry1
11    fractal_dimension1
12               radius2
13              texture2
14            perimeter2
15                 area2
16           smoothness2
17          compactness2
18            concavity2
19       concave_points2
20             symmetry2
21    fractal_dimension2
22               radius3
23              texture3
24            perimeter3
25                 area3
26           smoothness3
27          compactness3
28            concavity3
29       concave_points3
30             symmetry3
31    fractal_dimension3
Name: name, dtype: object


In [11]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/11.1 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.1 MB 3.7 MB/s eta 0:00:03
   ------- -------------------------------- 2.1/11.1 MB 3.6 MB/s eta 0:00:03
   ----------------- ---------------------- 5.0/11.1 MB 4.7 MB/s eta 0:00:02
   ----------------------- ---------------- 6.6/11.1 MB 5.0 MB/s eta 0:00:01
   ------------------------------- -------- 8.7/11.1 MB 5.3 MB/s eta 0:00:01
   ------------------------------------- -- 10.5/11.1 MB 5.5 MB/s eta 0:00:01
   ---------------------------------------- 11.1/11.1 MB 5.3 MB/s eta 0:00:00
   ---------------------------------------- 0.0/43.6 MB ? eta -:--:--
   - -------------------------------------- 1.3/43.6 MB 6.1 MB/s eta 0:00:07
   -- ------------------------------------- 2.9/43.6 MB 6.2 MB/s eta 0:00:07
   --- ------------------------------------ 3.7/43.6 MB 5.7 MB/s eta 0:00:07
   ---- --


[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [12]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
import graphviz

In [33]:
type(X)

pandas.core.frame.DataFrame

In [43]:
y

Diagnosis
0           M
1           M
2           M
3           M
4           M
..        ...
564         M
565         M
566         M
567         M
568         B

[569 rows x 1 columns]

In [13]:
fn = list(X1.columns.values)

In [18]:
X = X1.values
y = y1.values

In [19]:
from sklearn.model_selection import train_test_split

# Split the data into 70% training and 30% testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print("X_train:", X_train)
print("X_test:", X_test)
print("y_train:", y_train)
print("y_test:", y_test)

X_train: [[1.374e+01 1.791e+01 8.812e+01 ... 6.019e-02 2.350e-01 7.014e-02]
 [1.337e+01 1.639e+01 8.610e+01 ... 8.978e-02 2.048e-01 7.628e-02]
 [1.469e+01 1.398e+01 9.822e+01 ... 1.108e-01 2.827e-01 9.208e-02]
 ...
 [1.429e+01 1.682e+01 9.030e+01 ... 3.333e-02 2.458e-01 6.120e-02]
 [1.398e+01 1.962e+01 9.112e+01 ... 1.827e-01 3.179e-01 1.055e-01]
 [1.218e+01 2.052e+01 7.722e+01 ... 7.431e-02 2.694e-01 6.878e-02]]
X_test: [[1.247e+01 1.860e+01 8.109e+01 ... 1.015e-01 3.014e-01 8.750e-02]
 [1.894e+01 2.131e+01 1.236e+02 ... 1.789e-01 2.551e-01 6.589e-02]
 [1.546e+01 1.948e+01 1.017e+02 ... 1.514e-01 2.837e-01 8.019e-02]
 ...
 [9.904e+00 1.806e+01 6.460e+01 ... 9.910e-02 2.614e-01 1.162e-01]
 [1.382e+01 2.449e+01 9.233e+01 ... 1.521e-01 3.651e-01 1.183e-01]
 [1.289e+01 1.411e+01 8.495e+01 ... 1.561e-01 2.639e-01 1.178e-01]]
y_train: [['B']
 ['B']
 ['B']
 ['B']
 ['B']
 ['M']
 ['B']
 ['B']
 ['B']
 ['B']
 ['B']
 ['B']
 ['M']
 ['M']
 ['M']
 ['B']
 ['B']
 ['M']
 ['B']
 ['M']
 ['B']
 ['B']
 ['B

In [20]:
clf = DecisionTreeClassifier()
# Train the classifier
clf.fit(X_train, y_train)


DecisionTreeClassifier()

In [21]:
y_pred_tree = clf.predict(X_test)

In [22]:
from sklearn.metrics import accuracy_score

# Calculate accuracy
accuracy = accuracy_score(y_test, y_pred_tree)
print("Accuracy:", accuracy)


Accuracy: 0.935672514619883


In [23]:
# Visualize the decision tree
dot_data = tree.export_graphviz(clf, out_file=None,
feature_names=fn,
class_names=['M', 'B'],
filled=True, rounded=True,
special_characters=True)
graph = graphviz.Source(dot_data)
graph.render("decision_tree_example")
# Saves the tree as a PDF file
graph.view()

'decision_tree_example.pdf'

In [24]:
from sklearn.neighbors import KNeighborsClassifier

In [26]:
knn = KNeighborsClassifier(n_neighbors=5)

In [27]:
knn.fit(X_train, y_train)

C:\Users\Ngaire\AppData\Roaming\Python\Python312\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [28]:
y_pred = knn.predict(X_test)

In [29]:
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy * 100:.2f}%')

Accuracy: 95.91%
